Alice: Ariadne

BotSession:
    host: http://localhost:8080 # host of the bot
    account: 000000001 # account of the bot
    verify_key: 123456789 # verify key of the bot

ApiKey: 
    Baidu:
        APIKEY: xxxxxxxxxxxx # Baidu API key
        SECRETKEY: xxxxxxxxxxxx # Baidu API secret key
    Github:
        Token: xxxxxxxxxxxx # Github API token
    Bilibili:
        bili_jct: xxxxxxxxxxxx # Bilibili JCT
        sessdata: xxxxxxxxxxxx # Bilibili session data
        buvid3: xxxxxxxxxxxx # Bilibili buvid3

SSH:
    host: xxx.xxx.xxx.xxx # host of the linux ssh
    port: 22 # port of the linux ssh
    username: root # username of the linux ssh
    password: xxxxxxxxxxxx # password of the linux ssh